# Generated by Django 2.2 on 2020-03-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='lizard_apps/')),
                ('name', models.CharField(db_index=True, help_text='Descriptive text for labeling the icon', max_length=64)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('url', 'icon', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Application')),
            ],
            options={
                'ordering': ['screen', 'order', 'application__name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('applications', models.ManyToManyField(related_name='screens', through='myapp.ApplicationScreen', to='myapp.Application')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='applicationscreen',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Screen'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationscreen',
            unique_together={('screen', 'application')},
        ),
    ]
