# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='lizard_apps/')),
                ('name', models.CharField(db_index=True, help_text='Descriptive text for labeling the icon', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizard_apps.Application')),
            ],
            options={
                'ordering': ['screen', 'order', 'application__name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('applications', models.ManyToManyField(related_name='screens', through='lizard_apps.ApplicationScreen', to='lizard_apps.Application')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='applicationscreen',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizard_apps.Screen'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationscreen',
            unique_together=set([('screen', 'application')]),
        ),
    ]
