# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-23 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('url', 'icon', 'name')]),
        ),
    ]
